import "./globals.css";
import { Providers } from "@/components/Providers";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Gregory Taylor Photography",
  description: "Generated by Bria Strategy Group",
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' }
    ],
    shortcut: '/favicon-32x32.png',
    apple: '/apple-touch-icon.png',
    other: [
      { url: '/android-chrome-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/android-chrome-512x512.png', sizes: '512x512', type: 'image/png' }
    ]
  },
  openGraph: {
    images: [
      '/vercel.svg',
      '/next.svg',
      '/window.svg',
      '/globe.svg',
      '/file.svg'
    ]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Icons are handled by metadata.icons configuration */}
      </head>
      <body suppressHydrationWarning>
        <Providers>
          <Toaster position="top-right" />
          <div>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
